# Generated by Django 5.0 on 2025-05-13 08:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('phoneNumberTwo', models.CharField(blank=True, max_length=20, null=True)),
                ('instagramLink', models.URLField(blank=True, max_length=255, null=True)),
                ('tikTokLink', models.URLField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
